const strings = {
  en: {
    appName: "SwasthyaPath",
    appTagline: "Emergency hospital finder",
    emergencyLabel: "National Emergency",
    labelDescribe: "Describe the emergency",
    placeholder: "E.g. My father has severe chest pain and difficulty breathing for 20 minutes...",
    micLabel: "Voice input",
    triageLabel: "Find hospitals",
    loadingMessages: [
      "Analyzing symptoms...",
      "Finding nearby hospitals...",
      "Checking available facilities...",
      "Almost ready...",
    ],
    facilitiesNeeded: "Facilities needed",
    hospitalsFound: "Nearest hospitals with required facilities",
    bestMatch: "Best match",
    callBtn: "Call now",
    doNowLabel: "Do now",
    quickChips: [
      { label: "Chest pain", text: "Severe chest pain and breathlessness" },
      { label: "Road accident", text: "Major road accident, head injury and heavy bleeding" },
      { label: "Labour pain", text: "Pregnant woman in labour, baby coming soon" },
      { label: "Child seizure", text: "Child had convulsions and lost consciousness" },
      { label: "Snake bite", text: "Snake bite on leg, swelling and numbness spreading" },
    ],
  },

  hi: {
    appName: "स्वास्थ्यपथ",
    appTagline: "आपातकालीन अस्पताल खोजक",
    emergencyLabel: "राष्ट्रीय आपातकालीन",
    labelDescribe: "आपात स्थिति बताएं",
    placeholder: "जैसे: मेरे पिताजी को पिछले 20 मिनट से सीने में तेज दर्द और सांस लेने में बहुत तकलीफ हो रही है...",
    micLabel: "आवाज से बताएं",
    triageLabel: "अस्पताल खोजें",
    loadingMessages: [
      "लक्षणों का विश्लेषण हो रहा है...",
      "पास के अस्पताल खोजे जा रहे हैं...",
      "उपलब्ध सुविधाएं जांची जा रही हैं...",
      "लगभग तैयार है...",
    ],
    facilitiesNeeded: "आवश्यक सुविधाएं",
    hospitalsFound: "पास के अस्पताल जहाँ जरूरी सुविधाएं हैं",
    bestMatch: "सबसे उपयुक्त",
    callBtn: "अभी कॉल करें",
    doNowLabel: "अभी करें",
    quickChips: [
      { label: "सीने में दर्द", text: "सीने में तेज दर्द और सांस लेने में तकलीफ" },
      { label: "सड़क दुर्घटना", text: "सड़क दुर्घटना, सिर में चोट और खून बह रहा है" },
      { label: "प्रसव पीड़ा", text: "गर्भवती महिला को प्रसव पीड़ा, बच्चा जल्द आने वाला है" },
      { label: "बच्चे को दौरे", text: "बच्चे को दौरे पड़े और होश खो बैठा" },
      { label: "सांप का काटा", text: "पैर पर सांप का काटा, सूजन और सुन्नपन फैल रहा है" },
    ],
  },

  ta: {
    appName: "சுவாஸ்த்யபத்",
    appTagline: "அவசர மருத்துவமனை கண்டுபிடிப்பான்",
    emergencyLabel: "தேசிய அவசரநிலை",
    labelDescribe: "அவசரநிலையை விவரிக்கவும்",
    placeholder: "எ.கா: என் தந்தைக்கு 20 நிமிடங்களாக மார்பில் கடுமையான வலி மற்றும் மூச்சுத் திணறல் உள்ளது...",
    micLabel: "குரல் உள்ளீடு",
    triageLabel: "மருத்துவமனை கண்டுபிடி",
    loadingMessages: [
      "அறிகுறிகளை பகுப்பாய்வு செய்கிறோம்...",
      "அருகிலுள்ள மருத்துவமனைகளை தேடுகிறோம்...",
      "கிடைக்கும் வசதிகளை சரிபார்க்கிறோம்...",
      "கிட்டத்தட்ட தயாராகிவிட்டோம்...",
    ],
    facilitiesNeeded: "தேவையான வசதிகள்",
    hospitalsFound: "தேவையான வசதிகளுடன் அருகிலுள்ள மருத்துவமனைகள்",
    bestMatch: "சிறந்த பொருத்தம்",
    callBtn: "இப்போது அழைக்கவும்",
    doNowLabel: "இப்போது செய்யவும்",
    quickChips: [
      { label: "மார்பு வலி", text: "கடுமையான மார்பு வலி மற்றும் மூச்சுத் திணறல்" },
      { label: "சாலை விபத்து", text: "பெரிய சாலை விபத்து, தலையில் காயம் மற்றும் அதிக இரத்தப்போக்கு" },
      { label: "பிரசவ வலி", text: "கர்ப்பிணி பெண்ணுக்கு பிரசவ வலி, குழந்தை விரைவில் வருகிறது" },
      { label: "குழந்தைக்கு வலிப்பு", text: "குழந்தைக்கு வலிப்பு வந்து சுயநினைவு இழந்தது" },
      { label: "பாம்பு கடி", text: "காலில் பாம்பு கடித்தது, வீக்கம் மற்றும் உணர்வின்மை பரவுகிறது" },
    ],
  },

  te: {
    appName: "స్వాస్థ్యపథ్",
    appTagline: "అత్యవసర ఆసుపత్రి సోకనాన్వేషకుడు",
    emergencyLabel: "జాతీయ అత్యవసర పరిస్థితి",
    labelDescribe: "అత్యవసర పరిస్థితిని వివరించండి",
    placeholder: "ఉదా: నా తండ్రికి 20 నిమిషాల నుండి తీవ్రమైన ఛాతీ నొప్పి మరియు శ్వాస తీసుకోవడంలో ఇబ్బంది ఉంది...",
    micLabel: "వాయిస్ ఇన్‌పుట్",
    triageLabel: "ఆసుపత్రులు కనుగొనండి",
    loadingMessages: [
      "లక్షణాలు విశ్లేషిస్తున్నాం...",
      "దగ్గరలో ఉన్న ఆసుపత్రులు వెతుకుతున్నాం...",
      "అందుబాటులో ఉన్న సౌకర్యాలు తనిఖీ చేస్తున్నాం...",
      "దాదాపు సిద్ధంగా ఉంది...",
    ],
    facilitiesNeeded: "అవసరమైన సౌకర్యాలు",
    hospitalsFound: "అవసరమైన సౌకర్యాలతో దగ్గరలోని ఆసుపత్రులు",
    bestMatch: "అత్యుత్తమ సరిపోలిక",
    callBtn: "ఇప్పుడు కాల్ చేయండి",
    doNowLabel: "ఇప్పుడు చేయండి",
    quickChips: [
      { label: "ఛాతీ నొప్పి", text: "తీవ్రమైన ఛాతీ నొప్పి మరియు శ్వాస ఆడకపోవడం" },
      { label: "రోడ్డు ప్రమాదం", text: "పెద్ద రోడ్డు ప్రమాదం, తల గాయం మరియు భారీ రక్తస్రావం" },
      { label: "ప్రసవ వేదన", text: "గర్భిణీ స్త్రీకి ప్రసవ వేదన, పిల్లలు త్వరలో వస్తున్నారు" },
      { label: "పిల్లలకు మూర్ఛ", text: "పిల్లలకు మూర్ఛ వచ్చి స్పృహ కోల్పోయారు" },
      { label: "పాము కాటు", text: "కాలికి పాము కాటు, వాపు మరియు మొద్దుబారడం వ్యాపిస్తోంది" },
    ],
  },

  bn: {
    appName: "স্বাস্থ্যপথ",
    appTagline: "জরুরি হাসপাতাল খোঁজক",
    emergencyLabel: "জাতীয় জরুরি অবস্থা",
    labelDescribe: "জরুরি অবস্থা বর্ণনা করুন",
    placeholder: "যেমন: আমার বাবার ২০ মিনিট ধরে বুকে তীব্র ব্যথা এবং শ্বাস নিতে কষ্ট হচ্ছে...",
    micLabel: "ভয়েস ইনপুট",
    triageLabel: "হাসপাতাল খুঁজুন",
    loadingMessages: [
      "লক্ষণ বিশ্লেষণ করা হচ্ছে...",
      "কাছের হাসপাতাল খোঁজা হচ্ছে...",
      "উপলব্ধ সুবিধা যাচাই করা হচ্ছে...",
      "প্রায় প্রস্তুত...",
    ],
    facilitiesNeeded: "প্রয়োজনীয় সুবিধা",
    hospitalsFound: "প্রয়োজনীয় সুবিধাসহ নিকটতম হাসপাতাল",
    bestMatch: "সেরা মিল",
    callBtn: "এখনই কল করুন",
    doNowLabel: "এখনই করুন",
    quickChips: [
      { label: "বুকে ব্যথা", text: "তীব্র বুকে ব্যথা এবং শ্বাসকষ্ট" },
      { label: "সড়ক দুর্ঘটনা", text: "বড় সড়ক দুর্ঘটনা, মাথায় আঘাত এবং প্রচুর রক্তক্ষরণ" },
      { label: "প্রসব বেদনা", text: "গর্ভবতী মহিলার প্রসব বেদনা, শিশু শীঘ্রই আসছে" },
      { label: "শিশুর খিঁচুনি", text: "শিশুর খিঁচুনি হয়ে চেতনা হারিয়েছে" },
      { label: "সাপের কামড়", text: "পায়ে সাপের কামড়, ফোলা এবং অসাড়তা ছড়িয়ে পড়ছে" },
    ],
  },

  mr: {
    appName: "स्वास्थ्यपथ",
    appTagline: "आपत्कालीन रुग्णालय शोधक",
    emergencyLabel: "राष्ट्रीय आणीबाणी",
    labelDescribe: "आणीबाणी परिस्थिती सांगा",
    placeholder: "उदा: माझ्या वडिलांना गेल्या २० मिनिटांपासून छातीत तीव्र दुखणे आणि श्वास घेण्यास त्रास होत आहे...",
    micLabel: "आवाज इनपुट",
    triageLabel: "रुग्णालय शोधा",
    loadingMessages: [
      "लक्षणांचे विश्लेषण होत आहे...",
      "जवळपासची रुग्णालये शोधत आहोत...",
      "उपलब्ध सुविधा तपासत आहोत...",
      "जवळजवळ तयार...",
    ],
    facilitiesNeeded: "आवश्यक सुविधा",
    hospitalsFound: "आवश्यक सुविधांसह जवळची रुग्णालये",
    bestMatch: "सर्वोत्तम जुळणी",
    callBtn: "आत्ता कॉल करा",
    doNowLabel: "आत्ता करा",
    quickChips: [
      { label: "छातीत दुखणे", text: "तीव्र छातीत दुखणे आणि श्वास लागणे" },
      { label: "रस्ता अपघात", text: "मोठा रस्ता अपघात, डोक्याला दुखापत आणि जास्त रक्तस्त्राव" },
      { label: "प्रसूती वेदना", text: "गर्भवती महिलेला प्रसूती वेदना, बाळ लवकरच येणार" },
      { label: "मुलाला झटके", text: "मुलाला झटके येऊन शुद्ध हरपली" },
      { label: "सापाचा दंश", text: "पायाला सापाचा दंश, सूज आणि बधिरपणा पसरत आहे" },
    ],
  },
};

export default strings;